id = "zen"
name = "Zen"
version = "0.0.3"
schema_version = 1
authors = ["Kenny Heard <work@kennyheard.dev>"]
description = "Designed for clarity and focus."
repository = "https://github.com/kennyheard/zed-theme-zen"
